name: viumodel
description: ViewModel with destroyable property
version: 1.1.5
homepage: https://github.com/orgdonut/viewmodel

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

