name: tadpole
description: Flutter's Amphibian to link your data layer with the presenter layer with lifecycle aware properties
version: 0.1.0
homepage: https://github.com/orgdonut/viewmodel

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

